### ISSUE TITLE
The config is unavailable in public repositories

### ISSUE THREAD

**Issue by liamaharon** [hubiinetwork/eslint-config#2]
We need to make this repository public for it to be available in other public hubii repositories. 

Context: 
https://github.com/hubiinetwork/nahmii-sdk/issues/21, 
>morten [4:10 PM]
btw ive added and removed the eslint config many times already :stuck_out_tongue:
always forgets its a private repo

>Liam [4:11 PM]
can we just make the config public?

>morten [4:12 PM]
Maybe.. havent had the time to look into that repo and if there is anything we dont want public

>Liam [4:13 PM]
I took a look, there's literally only a readme, simple package.json and the lint rules
I'll open an issue there for Jon to review, just in case I am missing something

>morten [4:14 PM]
ok :+1:

@jonbern when you have a few minutes could you please confirm we're ok to make this public? Thanks!

**Comment by jonbern** [comment]
I've made it public now. There's no sensitive data in this repo, it's basically just a generic config.
